version: "3.9"

services:
  speeedy:
    build: .
    container_name: speeedy
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - webnet

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - webnet

volumes:
  caddy_data:
  caddy_config:

networks:
  webnet:
    driver: bridge

